---
- name: Deploy web application
  hosts: server1, server2, server3
  any_errors_fatal: yes
  tasks:
  block:
    - name: Install dependencies
        << code here >>
    - name: Install MySQL Database
        << code here >>
    - name: Start MySQL Service
        << code here >>
    - name: Install Python Flask dependencies
        << code here >>
    - name: Run web-server
        << code here >>

    - command: cat /var/log/server
      register: command_output
      failed_when: 'ERROR' in command_output.stdout
  rescue: 
  - mail:
        to: admin@company.com
        subject: Server configured
        body: Web server has been configured
